### PR TITLE
Increase decentralization of the Ecosystem project

### PR DESCRIPTION
**Pull request by erciccione**
I think the Ecosystem is mature enough to be more decentralized. With this PR i propose to introduce some substantial changes, that will take of some powers from me and put it in the ends of the maintainers of this project:

- Remove my veto right in the voting process.
- Give maintainers "Write" powers to this repository (increased from "Triage")
- Add the maintainers group (who manage and develop the Ecosystem project) as codeowner of the project.

codeowners have push rights (which i already activated), which means they are able to merge pull requests and push on this repository. Along with this change, i introduced the requirement for all PRs to be reviewed by at least 1 maintaienr (codeowner) before it will be possible to merge. That to avoid people bypassing the review process by opening a PR and merging it without a review.

*This PR introduces substantial changes to the government of the project. I encourage the @monero-ecosystem/maintainers to review (approve) the PR to signal their approval*

### CODE REVIEW

**Comment by erciccione** [comment]
ping @monero-ecosystem/maintainers

**Comment by emesik** [comment]
I think that the threshold of only 2 malicious users being able to mess things up is quite low. This is 11% of the current maintainers group, IIUC.

What is the policy of accepting new users? Who is able to do it?

**Comment by erciccione** [comment]
> I think that the threshold of only 2 malicious users being able to mess things up is quite low

I understand your concern, but rising that thresold means that the members of the maintainers team should be much more active in the maintainance of the repo. If we rise the thresold right now, i'm afraid PR will take long time to be merged. I agree would be better to rise it btw. Should we increase it to 2 and see how things goes? Reviewing the PRs in this repo is a matter of a couple of minutes at the end.

Btw "Write" powers are limited and not distructive (see https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level), if we also consider that this repo is basically composed by a markdown file, the ability to create actual damage to the project is basically non existent.

> What is the policy of accepting new users? Who is able to do it?

New maintainers come with new repos and that's voted as for our government process. The practical action of adding the maintainers can be done by the GitHub project owner (Me).

**Comment by erciccione** [comment]
> Should we increase it to 2 and see how things goes? 

On a second though, maybe would be better to use an higher threshold and, if necessary, decrease it. I propose to **raise the minimum amount of approvals to 3**

**Comment by emesik** [comment]
Sounds good to me now.

**Comment by erciccione** [comment]
I raised the threshold to 3.

**Comment by omani** [comment]
does this means I can't PR and merge into my own repos? so I need a second maintainer to review and approve it?

**Comment by vorot93** [comment]
It also appears that we have lost our privileges to move our repos back to personal account should such need arise.

**Comment by erciccione** [comment]
@omani this is only related to the meta repo. Everything else stay the same.

@vorot93 That doesn't seem to be related. I just checked and GitHub changed the structure of some settings and maybe i forgot to untick one option after the transfer of the last repo. Should be fixed now, please confirm.

**Comment by vorot93** [comment]
@erciccione confirmed

**Comment by omani** [comment]
ok thank you. Im all for it. +1

**Comment by erciccione** [comment]
Thank you all for the review. I suggest to leave this open for 24 hours before merging. I would like to give the possibility to everybody to comment if they want to. Please review #66 in the meantime, 2 reviews missing there :)

**Pull request merged**
